.create-merge table [record] (
   [type]: string,
   [postOfficeBox]: string,
   [extendedAddress]: string,
   [streetAddress]: string,
   [locality]: string,
   [region]: string,
   [postalCode]: string,
   [countryName]: string
);

.alter table [record] docstring "{\"description\": \"An address similar to http://microformats.org/wiki/h-card\"}";

.alter table [record] column-docstrings (
   [type]: "{\"description\": \"The type of the record\"}",
   [postOfficeBox]: "{\"description\": \"The post office box number\", \"type\": [\"null\", \"string\"]}",
   [extendedAddress]: "{\"description\": \"The extended address\", \"type\": [\"null\", \"string\"]}",
   [streetAddress]: "{\"description\": \"The street address\", \"type\": [\"null\", \"string\"]}",
   [locality]: "{\"description\": \"The locality\"}",
   [region]: "{\"description\": \"The region\"}",
   [postalCode]: "{\"description\": \"The postal code\", \"type\": [\"null\", \"string\"]}",
   [countryName]: "{\"description\": \"The country name\"}"
);

.create-or-alter table [record] ingestion json mapping "record_json_flat"
```
[
  {"column": "type", "path": "$.type"},
  {"column": "postOfficeBox", "path": "$.postOfficeBox"},
  {"column": "extendedAddress", "path": "$.extendedAddress"},
  {"column": "streetAddress", "path": "$.streetAddress"},
  {"column": "locality", "path": "$.locality"},
  {"column": "region", "path": "$.region"},
  {"column": "postalCode", "path": "$.postalCode"},
  {"column": "countryName", "path": "$.countryName"},
]
```

