.create-merge table [TelemetryRecord] (
   [id]: string,
   [version]: int,
   [channel]: string,
   [carId]: string,
   [intervalId]: string,
   [sampleCount]: long,
   [frequency]: long,
   [created]: long,
   [timespan]: dynamic,
   [data]: dynamic,
   [lapId]: string
);

.alter table [TelemetryRecord] docstring "{\"description\": \"Represents a telemetry record for a race car.\"}";

.alter table [TelemetryRecord] column-docstrings (
   [id]: "{\"description\": \"The unique identifier of the telemetry record.\", \"schema\": [\"null\", \"string\"]}",
   [version]: "{\"description\": \"The version of the telemetry record.\"}",
   [channel]: "{\"description\": \"The channel of the telemetry record.\"}",
   [carId]: "{\"description\": \"The identifier of the race car.\", \"schema\": [\"null\", \"string\"]}",
   [intervalId]: "{\"description\": \"The interval identifier of the telemetry record.\", \"schema\": [\"null\", \"string\"]}",
   [sampleCount]: "{\"description\": \"The sample count of the telemetry record.\"}",
   [frequency]: "{\"description\": \"The frequency of the telemetry record.\"}",
   [created]: "{\"description\": \"The creation timestamp of the telemetry record.\", \"schema\": [\"null\", \"long\"]}",
   [timespan]: "{\"description\": \"The timespan of the telemetry record.\", \"schema\": {\"name\": \"RecordRange\", \"type\": \"record\", \"fields\": [{\"name\": \"started\", \"type\": \"long\", \"doc\": \"The start timestamp of the telemetry record.\"}, {\"name\": \"ended\", \"type\": \"long\", \"doc\": \"The end timestamp of the telemetry record.\"}]}}",
   [data]: "{\"description\": \"The telemetry data.\", \"schema\": {\"type\": \"array\", \"items\": \"double\"}}",
   [lapId]: "{\"description\": \"The identifier of the lap.\", \"schema\": [\"null\", \"string\"]}"
);

.create-or-alter table [TelemetryRecord] ingestion json mapping "TelemetryRecord_json_flat"
```
[
  {"column": "id", "path": "$.id"},
  {"column": "version", "path": "$.version"},
  {"column": "channel", "path": "$.channel"},
  {"column": "carId", "path": "$.carId"},
  {"column": "intervalId", "path": "$.intervalId"},
  {"column": "sampleCount", "path": "$.sampleCount"},
  {"column": "frequency", "path": "$.frequency"},
  {"column": "created", "path": "$.created"},
  {"column": "timespan", "path": "$.timespan"},
  {"column": "data", "path": "$.data"},
  {"column": "lapId", "path": "$.lapId"},
]
```

