"""Convert Avrotize/Avro schemas to Cap'n Proto .capnp schemas."""

from __future__ import annotations

import json
import os
import re
import tempfile
from typing import Any

INDENT = "  "
FILE_ID = "0xd12f8a7e9b0c4a6f"


def _safe_ident(name: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not safe or safe[0].isdigit():
        safe = f"_{safe}"
    return safe


def _type_name(schema: dict[str, Any]) -> str:
    namespace = schema.get("namespace")
    name = schema["name"]
    return f"{namespace}.{name}" if namespace else name


class AvroToCapnpConverter:
    primitive_map = {
        "null": "Void",
        "boolean": "Bool",
        "int": "Int32",
        "long": "Int64",
        "float": "Float32",
        "double": "Float64",
        "bytes": "Data",
        "string": "Text",
    }

    def __init__(self, namespace: str | None = None) -> None:
        self.namespace = namespace
        self.named: dict[str, dict[str, Any]] = {}
        self.emitted: set[str] = set()

    def convert(self, avro_schema: Any) -> str:
        schemas = avro_schema if isinstance(avro_schema, list) else [avro_schema]
        for schema in schemas:
            if isinstance(schema, dict) and schema.get("type") in {"record", "enum"}:
                self.named[schema["name"]] = schema
                self.named[_type_name(schema)] = schema
        lines = [f"@{FILE_ID};", ""]
        if self.namespace:
            lines.append(f"# namespace: {self.namespace}")
        lines.append("# Generated by avrotize. File id is stable for deterministic output; replace if needed.")
        lines.append("")
        for schema in schemas:
            if isinstance(schema, dict) and schema.get("type") in {"enum", "record"}:
                name = _type_name(schema)
                if name not in self.emitted:
                    lines.extend(self._render_named(schema, 0))
                    lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _render_named(self, schema: dict[str, Any], level: int) -> list[str]:
        if schema.get("type") == "enum":
            return self._render_enum(schema, level)
        if schema.get("type") == "record":
            return self._render_struct(schema, level)
        return []

    def _render_enum(self, schema: dict[str, Any], level: int) -> list[str]:
        self.emitted.add(_type_name(schema))
        lines = [f"{INDENT * level}enum {_safe_ident(schema['name'])} {{"]
        for index, symbol in enumerate(schema.get("symbols", [])):
            lines.append(f"{INDENT * (level + 1)}{_safe_ident(symbol)} @{index};")
        lines.append(f"{INDENT * level}}}")
        return lines

    def _render_struct(self, schema: dict[str, Any], level: int) -> list[str]:
        self.emitted.add(_type_name(schema))
        lines = [f"{INDENT * level}struct {_safe_ident(schema['name'])} {{"]
        fields = schema.get("fields", [])
        grouped: dict[str, list[tuple[int, dict[str, Any], Any]]] = {}
        normal: list[tuple[int, dict[str, Any], Any]] = []
        for index, field in enumerate(fields):
            avro_type = field.get("type")
            union_name = field.get("capnpUnion")
            item = (index, field, avro_type)
            if union_name:
                grouped.setdefault(str(union_name), []).append(item)
            else:
                normal.append(item)
        for index, field, avro_type in normal:
            lines.extend(self._render_field(field, avro_type, index, level + 1))
        for _, items in grouped.items():
            lines.append(f"{INDENT * (level + 1)}union {{")
            for index, field, avro_type in items:
                lines.extend(self._render_field(field, avro_type, index, level + 2))
            lines.append(f"{INDENT * (level + 1)}}}")
        lines.append(f"{INDENT * level}}}")
        return lines

    def _render_field(self, field: dict[str, Any], avro_type: Any, index: int, level: int) -> list[str]:
        capnp_type, nested = self._capnp_type(avro_type, _safe_ident(field.get("name", f"field{index}")))
        ordinal = index
        lines: list[str] = []
        lines.extend(self._render_inline_nested(nested, level))
        lines.append(f"{INDENT * level}{_safe_ident(field.get('name', f'field{index}'))} @{ordinal} :{capnp_type};")
        return lines

    def _render_inline_nested(self, nested: list[dict[str, Any]], level: int) -> list[str]:
        lines: list[str] = []
        for schema in nested:
            lines.extend(self._render_named(schema, level))
        return lines

    def _non_null_union(self, avro_type: list[Any]) -> list[Any]:
        return [item for item in avro_type if item != "null" and not (isinstance(item, dict) and item.get("type") == "null")]

    def _capnp_type(self, avro_type: Any, field_name: str) -> tuple[str, list[dict[str, Any]]]:
        if isinstance(avro_type, list):
            non_null = self._non_null_union(avro_type)
            if len(non_null) == 1:
                return self._capnp_type(non_null[0], field_name)
            union_schema = {
                "type": "record",
                "name": f"{field_name[:1].upper()}{field_name[1:]}Choice",
                "fields": [{"name": f"choice{i}", "type": t, "capnpUnion": "union"} for i, t in enumerate(non_null)],
            }
            return union_schema["name"], [union_schema]
        if isinstance(avro_type, dict):
            avro_kind = avro_type.get("type")
            if isinstance(avro_kind, list):
                return self._capnp_type(avro_kind, field_name)
            if avro_kind == "array":
                item_type, nested = self._capnp_type(avro_type.get("items", "string"), f"{field_name}Item")
                return f"List({item_type})", nested
            if avro_kind == "map":
                entry = {
                    "type": "record",
                    "name": f"{field_name[:1].upper()}{field_name[1:]}Entry",
                    "fields": [
                        {"name": "key", "type": "string"},
                        {"name": "value", "type": avro_type.get("values", "string")},
                    ],
                }
                return f"List({entry['name']})", [entry]
            if avro_kind == "record":
                return avro_type["name"], [avro_type]
            if avro_kind == "enum":
                return avro_type["name"], [avro_type]
            if avro_kind == "fixed":
                return "Data", []
            return self._capnp_type(avro_kind, field_name)
        if isinstance(avro_type, str):
            named = self.named.get(avro_type)
            if named:
                return named["name"], []
            return self.primitive_map.get(avro_type, avro_type.split(".")[-1]), []
        return "Text", []


def convert_avro_to_capnproto(avro_schema_path: str, capnp_file_path: str, namespace: str | None = None) -> None:
    """Convert an Avrotize/Avro schema file to a Cap'n Proto .capnp schema file."""
    with open(avro_schema_path, "r", encoding="utf-8") as avro_file:
        avro_schema = json.load(avro_file)
    converter = AvroToCapnpConverter(namespace=namespace)
    capnp_schema = converter.convert(avro_schema)
    os.makedirs(os.path.dirname(os.path.abspath(capnp_file_path)) or ".", exist_ok=True)
    with open(capnp_file_path, "w", encoding="utf-8") as capnp_file:
        capnp_file.write(capnp_schema)


def convert_json_structure_to_capnproto(structure_file: str, capnp_file_path: str, namespace: str | None = None) -> None:
    """Convert JSON Structure to Cap'n Proto by bridging through Avrotize/Avro."""
    from avrotize.jstructtoavro import convert_json_structure_to_avro

    temp_parent = os.path.dirname(os.path.abspath(capnp_file_path)) or os.getcwd()
    os.makedirs(temp_parent, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="avrotize-capnp-", dir=temp_parent) as temp_dir:
        avro_file = os.path.join(temp_dir, "schema.avsc")
        convert_json_structure_to_avro(structure_file, avro_file)
        convert_avro_to_capnproto(avro_file, capnp_file_path, namespace=namespace)
