
"""Avrotize Schema to Apache Thrift IDL converter."""

from __future__ import annotations

import json
import os
import re
from typing import Any

from avrotize.thrifttoavro import sanitize_name, sanitize_namespace


_PRIMITIVE_TO_THRIFT = {
    "boolean": "bool",
    "int": "i32",
    "long": "i64",
    "float": "double",
    "double": "double",
    "bytes": "binary",
    "string": "string",
    "null": "void",
}


class AvroToThriftConverter:
    def __init__(self, namespace: str | None = None) -> None:
        self.namespace = sanitize_namespace(namespace) if namespace else None
        self.named: dict[str, dict[str, Any]] = {}

    def convert(self, avro_schema_path: str) -> str:
        with open(avro_schema_path, "r", encoding="utf-8") as avro_file:
            schema = json.load(avro_file)
        schemas = schema if isinstance(schema, list) else [schema]
        for item in schemas:
            if isinstance(item, dict) and item.get("type") in {"record", "enum"}:
                self.named[self.qname(item)] = item
                self.named[item["name"]] = item
        namespace = self.namespace or self.first_namespace(schemas)
        lines: list[str] = ["// Generated by avrotize from Avrotize Schema."]
        if namespace:
            lines.append(f"namespace * {namespace}")
        lines.append("")
        for item in schemas:
            if not isinstance(item, dict):
                continue
            if item.get("type") == "enum":
                lines.extend(self.render_enum(item))
                lines.append("")
            elif item.get("type") == "record":
                lines.extend(self.render_record(item))
                lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def first_namespace(self, schemas: list[Any]) -> str:
        for item in schemas:
            if isinstance(item, dict) and item.get("namespace"):
                return sanitize_namespace(item["namespace"])
        return ""

    def qname(self, schema: dict[str, Any]) -> str:
        return f"{schema.get('namespace')}.{schema['name']}" if schema.get("namespace") else schema["name"]

    def render_enum(self, schema: dict[str, Any]) -> list[str]:
        lines = [f"enum {sanitize_name(schema['name'])} {{"]
        ordinals = schema.get("ordinals", {})
        for index, symbol in enumerate(schema.get("symbols", [])):
            value = ordinals.get(symbol, index)
            lines.append(f"  {sanitize_name(symbol)} = {value};")
        lines.append("}")
        return lines

    def render_record(self, schema: dict[str, Any]) -> list[str]:
        keyword = "struct"
        doc = schema.get("doc", "")
        if "Converted from a Thrift exception" in doc:
            keyword = "exception"
        lines = [f"{keyword} {sanitize_name(schema['name'])} {{"]
        for index, field in enumerate(schema.get("fields", []), start=1):
            field_type, optional = self.field_type(field.get("type", "string"))
            requiredness = "optional" if optional else "required"
            default = self.render_default(field.get("default"), optional)
            lines.append(f"  {index}: {requiredness} {field_type} {sanitize_name(field.get('name', f'field_{index}'))}{default};")
        lines.append("}")
        return lines

    def field_type(self, avro_type: Any) -> tuple[str, bool]:
        optional = False
        if isinstance(avro_type, list):
            non_null = [t for t in avro_type if t != "null"]
            optional = len(non_null) != len(avro_type)
            avro_type = non_null[0] if non_null else "string"
            if len(non_null) > 1:
                return "string", optional
        return self.thrift_type(avro_type), optional

    def thrift_type(self, avro_type: Any) -> str:
        if isinstance(avro_type, str):
            if avro_type in _PRIMITIVE_TO_THRIFT:
                return _PRIMITIVE_TO_THRIFT[avro_type]
            return sanitize_name(avro_type.split(".")[-1])
        if isinstance(avro_type, list):
            return self.field_type(avro_type)[0]
        if isinstance(avro_type, dict):
            type_name = avro_type.get("type")
            if isinstance(type_name, list):
                return self.field_type(type_name)[0]
            if type_name in _PRIMITIVE_TO_THRIFT:
                return _PRIMITIVE_TO_THRIFT[type_name]
            if type_name == "array":
                return f"list<{self.thrift_type(avro_type.get('items', 'string'))}>"
            if type_name == "map":
                return f"map<string, {self.thrift_type(avro_type.get('values', 'string'))}>"
            if type_name in {"record", "enum"}:
                return sanitize_name(avro_type.get("name", "Anonymous"))
            if isinstance(type_name, str):
                return self.thrift_type(type_name)
        return "string"

    def render_default(self, value: Any, optional: bool) -> str:
        if value is None or optional:
            return ""
        if isinstance(value, bool):
            return " = true" if value else " = false"
        if isinstance(value, (int, float)):
            return f" = {value}"
        if isinstance(value, str):
            escaped = value.replace('\\', '\\\\').replace('"', '\\"')
            return f' = "{escaped}"'
        return ""


def convert_avro_to_thrift(avro_schema_path: str, thrift_file_path: str, namespace: str | None = None):
    """Convert Avrotize Schema to Apache Thrift IDL."""
    if not os.path.exists(avro_schema_path):
        raise FileNotFoundError(f"Avro schema file {avro_schema_path} does not exist.")
    converter = AvroToThriftConverter(namespace)
    thrift = converter.convert(avro_schema_path)
    with open(thrift_file_path, "w", encoding="utf-8") as thrift_file:
        thrift_file.write(thrift)
