name: Python Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up .NET SDK 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft' 
        java-version: '21'
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.12.0
      with:
        java-version: 21
        maven-version: '3.9.6'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1
    # we need to build the package for generating the _version.py file that isn't checked in
    - name: Install dependencies and build package
      run: |
        python -m pip install --upgrade pip build wheel
        python -m pip install pylint
        python -m pip install -r requirements.txt
        python -m build --sdist --wheel --outdir dist
    - name: Install dependencies
      run: pip install pytest pytest-md pytest-emoji
    - name: Run pytest
      uses: pavelzw/pytest-action@v2
      with:
        verbose: true
        emoji: true
        job-summary: false
        click-to-expand: true
        report-title: 'Test Report'

